# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190129_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
